document.write('<!DOCTYPE html>');
document.write('<html lang="en" >');
document.write('<head>');
document.write('  <meta charset="UTF-8">');
document.write('  <title>Chatroom</title>');
document.write('  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900">');
document.write('');
document.write('<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">');
document.write('<meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">');
document.write('<link rel="stylesheet" href="./style.css">');
document.write('');
document.write('</head>');
document.write('<body>');
document.write('<!-- partial:index.partial.html -->');
document.write('<div class="wrapper"></div>');
document.write('');
document.write('<input class="message" type="text" placeholder="Enter message and press enter"/>');
document.write('');
document.write('<div class="initModal">');
document.write('	<h3>What\'s your name?</h3>');
document.write('	<input type="text" class="username" placeholder="Enter your name and press enter"/>');
document.write('</div>');
document.write('<!-- partial -->');
document.write('  <script src=\'//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js\'></script>');
document.write('<script src=\'https://cdn.firebase.com/js/client/2.4.1/firebase.js\'></script><script  src="./script.js"></script>');
document.write('');
document.write('</body>');
document.write('</html>');
